name: iot
description: Monitoring Solar

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.2.0
  # dio: ^1.0.14
  intl: ^0.16.0
  path: ^1.6.4
  rxdart: ^0.20.0
  provider: ^2.0.0
  shared_preferences: ^0.5.7+3
  font_awesome_flutter:
  datetime_picker_formfield: 1.0.0
  carousel_slider: ^1.3.0
  fluttertoast: ^3.1.0
  cloud_firestore: ^0.13.6
  expandable: ^4.1.4
  flutter_launcher_icons: ^0.7.3
  cupertino_icons: ^0.1.2
  dynamic_theme: ^1.0.1
  eva_icons_flutter: ^2.0.0
  flare_flutter: ^1.8.1
  gradient_widgets: ^0.5.0
  firebase_database: ^3.1.6
  material_switch: ^0.0.5
  liquid_swipe: '1.2.0'
  # url_launcher: ^5.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/images/logo_pln.png"
  image_path_ios: "assets/images/logo_pln.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/credits/
    - assets/flare/
    - assets/icon/
    - assets/music/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik/Rubik-Italic.ttf
          style: italic

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Medium.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
